#+TITLE: Techela - Technology Enhanced Learning and Assessment
#+AUTHOR: John Kitchin

* Introduction

Techela is a framework for teaching courses. It provides a way to distribute, collect, grade, and return digital assignments.

* Initial server setup
The initial setup of a techela course on the techela server is described here. For this example, we create a course with a label of su16-org. You should create a course "recipe" and put it in the courses folder of techela. Here is an example of the recipe. This registers the course with techela.

#+BEGIN_SRC emacs-lisp :tangle courses/su16-org
(su16-org
 :title "Short course in org-mode"
 :course-number "N/A"
 :year 2016
 :semester "Summer"
 :instructor "John Kitchin"
 :instructor-email "jkitchin@andrew.cmu.edu"
 :course-repo "https://github.com/KitchinHUB/kitchingroup"
 :techela-server "su16-org@techela.cheme.cmu.edu")
#+END_SRC

** Create a new user on the server
The server is run on an ordinary Linux server under a dedicated user. The username should match the username in the :techela-server property of the course recipe. Here are two commands to create a new user and password for the user.

#+BEGIN_SRC sh
ssh root@techela.cheme.cmu.edu useradd  su16-org
#+END_SRC

#+BEGIN_SRC sh
ssh root@techela.cheme.cmu.edu passwd su16-org
#+END_SRC
#+RESULTS:

** install gitolite
gitolite is the git server we use to create and manage git repositories for the course. First, login as the user for the course, and then run these commands.

#+BEGIN_SRC sh
git clone git://github.com/sitaramc/gitolite
cd $HOME
mkdir bin
gitolite/install --to $HOME/bin
#+END_SRC

You need to get your ssh pub key in the directory. If you don't have a key already, generate one like this. I suggest you make it password free. This increases the risk of someone being able to use your key, but they need access to your machine to get it.

#+BEGIN_SRC sh
ssh-keygen -t rsa -f "your@email.address" -N ""
#+END_SRC

Then, from your local machine, run this.

#+BEGIN_SRC sh
scp ~/.ssh/id_rsa.pub su16-org@techela.cheme.cmu.edu:your@email.address.pub
#+END_SRC

Then, on the remote git server machine run this:
#+BEGIN_SRC sh
gitolite setup -pk your@email.address.pub
#+END_SRC

NOTE: the admin username is 'johnrkitchin+admin@gmail.com'
Initialized empty Git repository in /home/su16-org/repositories/gitolite-admin.git/
Initialized empty Git repository in /home/su16-org/repositories/testing.git/
WARNING: /home/su16-org/.ssh missing; creating a new one
    (this is normal on a brand new install)
WARNING: /home/su16-org/.ssh/authorized_keys missing; creating a new one
    (this is normal on a brand new install)

** clone the admin repo
Create a directory somewhere on your remote machine where you want the course to live. Then, clone the admin repo into it.

#+BEGIN_SRC sh
mkdir ~/techela/su16-org
cd ~/techela/su16-org
git clone su16-org@techela.cheme.cmu.edu:gitolite-admin
#+END_SRC

** edit gitolite/gitolite.conf
Go ahead and configure git if you have not already done so.

  git config --global user.email "jkitchin@andrew.cmu.edu"
  git config --global user.name "John Kitchin"

Now, we create the course repo. This is the repo that all students will have access to. We define the @instructors team


Add this to gitolite-admin/conf/gitolite.conf.

#+BEGIN_EXAMPLE
repo gitolite-admin
    RW+     =   johnrkitchin+admin@gmail.com

@instructors = jkitchin@andrew.cmu.edu
# file containing all student usernames
include "students.conf"

repo @all
    RW+ = jkitchin@andrew.cmu.edu
    RW = @instructors

# public course for students
repo course
    RW+ = jkitchin@andrew.cmu.edu
    RW = @instructors
    R = @students

# we create a single file for each student repo.
# the repos are grouped in the student-work directory.
include "student-work/*/*.conf"

# enable convenient creation of assignment repos. I can just clone
# these to make it work. When you push to these, they are readable to
# the students. This might be problematic if they clone them to
# early. They will have to pull again. But it makes it trivial to
# create the assignments without getting into the conf file.
#
# git clone su16-org@techela.cheme.cmu.edu:assignments/label
#
# automatically creates the repo. To give students read access, run
# this command.
#
# ssh su16-org@techela.cheme.cmu.edu perms assignments/label + READERS @students
repo assignments/[a-z].*
    C = jkitchin@andrew.cmu.edu
    RW+ = jkitchin@andrew.cmu.edu
    R = READERS

# wild-repo for the solutions
#
# git clone su16-org@techela.cheme.cmu.edu:solutions/label
#
# to add read permission
# ssh su16-org@techela.cheme.cmu.edu perms solutions/label + READERS @students
# to remove read permission
# ssh su16-org@techela.cheme.cmu.edu perms solutions/label - READERS @students
repo solutions/[a-z].*
    C = jkitchin@andrew.cmu.edu
    RW+ = jkitchin@andrew.cmu.edu
    R = READERS
#+END_EXAMPLE

Now, we create a non-empty directory for the student work configuration filesso we can commit it, and touch the students.conf file.
#+BEGIN_SRC sh
mkdir gitolite-admin/conf/student-work
echo "student repo conf files go here." > gitolite-admin/conf/student-work/README.org

echo "@students= " > conf/students.conf
#+END_SRC

That creates the course repo, and sets up the directories and files we need to create student repos. You have to commit and push these changes too.

#+BEGIN_SRC sh
git add student-work conf/students.conf
git commit -m "add students.conf and repos"
git push
#+END_SRC


* Course setup in gitolite-admin
This section describes the "private" course setup, i.e. the part students do not need to see.

** keydir
gitolite requirement. Contains userid.pub files.

** conf
gitolite requirement. Contains gitolite.conf, which sets up repos.

*** conf/student-work
We can actually create repo.conf files in this directory, and they are included in the gitolite.conf automatically. We only make one repo.conf per repository.

*** conf/students.conf
This file defines the @students group. It is usually generated automatically from the roster.
Initially this file should have these contents:

#+BEGIN_EXAMPLE
@students =
#+END_EXAMPLE

** gradebook
This directory contains a grading file for each assignment. The files contain links to each file, and a summary of the grades.

** ../course
This is the student facing part of the course. The syllabus should go in here, and any course notes/materials. This is a separate git repository that is usually publicly visible.

** ../student-work
Student repos will be cloned into this directory. This is where their work will be pulled after it is collected.

** ../class-work
Class repos will be cloned here. This is where you pull class repos for analysis.

** ../assignments
Assignments are referred to by label. There should be a directory with the name "label" for each assignment. The contents of this directory will be copied to student repos, so do not put solutions here!

Each assignment should also contain #+POINTS, #+CATEGORY and #+DUEDATE information, which is added to the syllabus when you use elisp:tq-assign-assignment

You create a new assignment repo simply by:

#+BEGIN_SRC sh
git clone su16-org@techela.cheme.cmu.edu:assignments/label
#+END_SRC

This automatically creates the remote repo and local directory. Then, you add your content to it and push it back. You have to separately assign it.

* Running your course
** TODO Create assignments
Assignments exist in a file called assignments.org in the gitolite-admin directory. Problems are in headlines with a CUSTOM_ID, and solutions should be in a subheading tagges with :solution:.

** TODO Assign assignments
Assignment is a multistep process. First, you create the assignment, commit and push it to the server. This is done in one of two ways:
1. In the assignments directory, run 
#+BEGIN_SRC sh
git clone su16-org@techela.cheme.cmu.edu:assignments/label
#+END_SRC

Create the content in the label directory, commit it and push it.

2. Run a command to create the repo from the assignments.org file.

Then, you need to create repos for each student. This is done with elisp:tq-create-assignment-repos. That will create repos for each student that are empty, and with no access for the students. Next, you assign an assignment with elisp:tq-assign-assignment. This will give students access to the assignment, and give them RW access to their repo to turn it in. Finally, an entry in the syllabus is added so the students will know when it is due.


** Collect assignments
There are a few steps in collecting an assignment too. The fastest step is to run elisp:tq-collect, which simply changes the student repos to read-only. To view the work, you must run elisp:tq-pull-repos, which will pull all the student work to your local repo.

** Grade assignments
You run elisp:tq-grade, which will collect the assignment, pull them, and generate a grading document with links to each assignment. You will click on each link to grade each assignment. In each assignment, provide feedback and finally elisp:gb-grade. You will be prompted for a letter grade for each category of the rubric. This function will compute the weighted average grade.

** Returning assignments
Run elisp:tq-return to commit all changes to each student repo and push them back to the server.

* FAQ
** Can I do teams?
 Yes. You can define teams in gitolite-admin/gitolite.conf like this:

 #+BEGIN_EXAMPLE
@team-1 = userid1 userid2 userid3
 #+END_EXAMPLE

 Then, you can create repos with team access like this:

 #+BEGIN_EXAMPLE
repo team-project-1
    RW = @team-1
 #+END_EXAMPLE

** Can students turn in a Word document? or a PPT presentation? Or a ...?
 Any kind of file can be turned in. Simply put a copy of the file into the assignment directory and run the tq-turn-it-in command.  All files in the directory will be turned in.

** Do I have to use Emacs or org-mode?
Not really, but sort of. Techela is a git based framework for distributing and collecting course materials. You can use git any way you want. However, you will have to roll your own solutions to use another method, e.g. Python or shell script. You will also not be able to get the integrated syllabus/grading tools that only exist in org-mode + Emacs.

*** Create assignment repos
 As an instructor you create an assignment repo like this:
 #+BEGIN_SRC sh
git clone org-course@techela.cheme.cmu.edu:a/label

cd label
# Add files
git add files
git commit files -m "some message"
git push -u origin master
 #+END_SRC


 When it is time to assign the assignment to students, you need to create private repos for each student. While these can be any path you want, I you make them like this. For each student, create a file in the gitolite-admin/conf/student-work/label/userid-label.conf with the following contents.

 #+BEGIN_EXAMPLE
repo student-work/label/userid-label
    RW = userid
 #+END_EXAMPLE

 When you have created all of them, do this in the gitolite-admin directory:

 #+BEGIN_SRC sh
git add conf/student-work
git commit -m "add new assignment repos"
git push
 #+END_SRC

 This creates bare repos on the server that students can access.

 Then, you run this command to give students read access to the assignment repo.

 #+BEGIN_SRC sh
ssh org-course@techela.cheme.cmu.edu perms + READERS @students
 #+END_SRC

 Students will run this command to clone the repo to their local machine. They only have read permission on this repo so they need to change the remote they will push to.

 #+BEGIN_SRC sh
git clone org-course@techela.cheme.cmu.edu:a/label
cd label
git remote rename origin src
git remote add origin org-course@techela.cheme.cmu.edu:student-work/label/userid-label
 #+END_SRC

 They will do their work in the label directory, and when they are done perform the following commands.
 #+BEGIN_SRC sh
git add *
git commit -am "Turning work in"
git push -u origin master
 #+END_SRC

*** Collecting the assignments
 You need to change the conf file for each assignment repo to have the correct permissions, in this case, read-only for the students like this.

 #+BEGIN_EXAMPLE
repo student-work/label/userid-label
    R = userid
 #+END_EXAMPLE

 When you have modified all of them, do this in the gitolite-admin directory:

 #+BEGIN_SRC sh
git add conf/student-work
git commit -m "add new assignment repos"
git push
 #+END_SRC

 Now, you need to clone/pull each repo to your local machine. The first time you do this, you will have to clone them, e.g.

 #+BEGIN_SRC sh
cd student-work/label/userid-label
git clone org-course@techela.cheme.cmu.edu:student-work/label/userid-label
cd user-label
git tag -a turned-in -m "Work turned in by student" 
 #+END_SRC

 You will do your grading, and then run this command to "return" the work.

 #+BEGIN_SRC sh
git tag -a graded -m "graded" 
git add *
git commit -am "Finished grading"
git push --tags -u origin master
 #+END_SRC

 Finally, students need to pull their repo to see the grade and feedback. 
